#!/usr/bin/env python3
"""Compile the pinned Android Java oracle and emit data for C++ tests."""

import argparse
import hashlib
from pathlib import Path
import subprocess


def signed_literal(value):
    if value == -(1 << 63):
        return "(-INT64_C(9223372036854775807) - 1)"
    return ("-" if value < 0 else "") + "INT64_C(" + str(abs(value)) + ")"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("source", "source-sha256", "java", "javac", "output"):
        parser.add_argument("--" + name, required=True)
    args = parser.parse_args()
    source = Path(args.source)
    if hashlib.sha256(source.read_bytes()).hexdigest() != args.source_sha256:
        raise ValueError("Android version oracle source hash mismatch")
    output = Path(args.output)
    classes = output.parent / "oracle-classes"
    classes.mkdir(parents=True, exist_ok=True)
    subprocess.run([args.javac, "-d", str(classes), str(source)], check=True)
    report = subprocess.check_output(
        [args.java, "-cp", str(classes), "AndroidPackageInfoOracle"], text=True
    )
    rows = [tuple(int(field) for field in line.split(","))
            for line in report.splitlines()]
    edges = (0, 0x7fffffff, 0x80000000, 0xffffffff)
    if len(rows) != 16 or any(len(row) != 6 for row in rows):
        raise ValueError("Expected exactly 16 complete Java oracle rows")
    if [(row[0], row[1]) for row in rows] != [(a, b) for a in edges for b in edges]:
        raise ValueError("Java oracle boundary input set mismatch")
    lines = [
        "// Generated by the pinned Java oracle. Do not edit.",
        "#ifndef OH_ADAPTER_VERSION_ORACLE_VALUES_H",
        "#define OH_ADAPTER_VERSION_ORACLE_VALUES_H",
        "#include <array>",
        "#include <cstdint>",
        "struct VersionOracleValue {",
        "    uint32_t major; uint32_t minor; uint64_t bits; int64_t javaLong;",
        "    uint32_t splitMajor; uint32_t splitMinor;",
        "};",
        "inline constexpr std::array<VersionOracleValue, 16> VERSION_ORACLE {{",
    ]
    for major, minor, bits, java_long, split_major, split_minor in rows:
        if not (0 <= bits < (1 << 64) and -(1 << 63) <= java_long < (1 << 63)):
            raise ValueError("Java oracle full value outside 64-bit domain")
        if any(not 0 <= part < (1 << 32)
               for part in (major, minor, split_major, split_minor)):
            raise ValueError("Java oracle part outside 32-bit domain")
        lines.append("    {UINT32_C(%d), UINT32_C(%d), UINT64_C(%d), %s, "
                     "UINT32_C(%d), UINT32_C(%d)}," %
                     (major, minor, bits, signed_literal(java_long),
                      split_major, split_minor))
    lines.extend(["}};", "#endif", ""])
    temporary = output.with_suffix(".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.replace(output)


if __name__ == "__main__":
    main()
