// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// com.android.i18n.phonenumbers.PhoneNumberUtil — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package com.android.i18n.phonenumbers;

public class PhoneNumberUtil {
    public PhoneNumberUtil() {}
    public static class Leniency {
        public Leniency() {}
    }
    public static class MatchType {
        public MatchType() {}
    }
    public static class PhoneNumberFormat {
        public PhoneNumberFormat() {}
    }
}
