// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.ipsec.ike.IkeSessionParams — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net.ipsec.ike;

public class IkeSessionParams {
    public IkeSessionParams() {}
    public static class Builder {
        public Builder() {}
    }
    public static class ConfigRequestIpv4PcscfServer {
        public ConfigRequestIpv4PcscfServer() {}
    }
    public static class ConfigRequestIpv6PcscfServer {
        public ConfigRequestIpv6PcscfServer() {}
    }
    public static class IkeAuthConfig {
        public IkeAuthConfig() {}
    }
    public static class IkeAuthDigitalSignLocalConfig {
        public IkeAuthDigitalSignLocalConfig() {}
    }
    public static class IkeAuthDigitalSignRemoteConfig {
        public IkeAuthDigitalSignRemoteConfig() {}
    }
    public static class IkeAuthEapConfig {
        public IkeAuthEapConfig() {}
    }
    public static class IkeAuthPskConfig {
        public IkeAuthPskConfig() {}
    }
    public static class IkeConfigRequest {
        public IkeConfigRequest() {}
    }
}
