// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.ipsec.ike.TunnelModeChildSessionParams — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net.ipsec.ike;

public class TunnelModeChildSessionParams {
    public TunnelModeChildSessionParams() {}
    public static class Builder {
        public Builder() {}
    }
    public static class ConfigRequestIpv4Address {
        public ConfigRequestIpv4Address() {}
    }
    public static class ConfigRequestIpv4DhcpServer {
        public ConfigRequestIpv4DhcpServer() {}
    }
    public static class ConfigRequestIpv4DnsServer {
        public ConfigRequestIpv4DnsServer() {}
    }
    public static class ConfigRequestIpv4Netmask {
        public ConfigRequestIpv4Netmask() {}
    }
    public static class ConfigRequestIpv6Address {
        public ConfigRequestIpv6Address() {}
    }
    public static class ConfigRequestIpv6DnsServer {
        public ConfigRequestIpv6DnsServer() {}
    }
    public static class TunnelModeChildConfigRequest {
        public TunnelModeChildConfigRequest() {}
    }
}
