/* OH6.1 direct platform boundary; generated from next4 boundary.json. */
#ifndef WESTLAKE_OH_DEPENDENCIES_H
#define WESTLAKE_OH_DEPENDENCIES_H
static const char kOhSharedDependencies[] =
    "libEGL.so"
    ":libGLESv3.so"
    ":libability_connect_callback_stub.z.so"
    ":libability_manager.z.so"
    ":libapp_manager.z.so"
    ":libappexecfwk_core.z.so"
    ":libappkit_native.z.so"
    ":libbegetutil.z.so"
    ":libc++.so"
    ":libcesfwk_innerkits.z.so"
    ":libclang_rt.ubsan_minimal.so"
    ":libconfiguration.z.so"
    ":libdatashare_consumer.z.so"
    ":libdm.z.so"
    ":libeventhandler.z.so"
    ":libhilog.so"
    ":libhitrace_ndk.z.so"
    ":libipc_single.z.so"
    ":libmission_info.z.so"
    ":libmmi-client.z.so"
    ":libnative_display_manager.so"
    ":libnative_drawing_ndk.z.so"
    ":libnative_vsync.so"
    ":librender_service_base.z.so"
    ":librender_service_client.z.so"
    ":libsamgr_proxy.z.so"
    ":libscene_session.z.so"
    ":libsession_manager.z.so"
    ":libskia_canvaskit.z.so"
    ":libsurface.z.so"
    ":libsync_fence.z.so"
    ":libutd_client.z.so"
    ":libutils.z.so"
    ":libwant.z.so"
    ":libwindow_scene_common.z.so"
    ":libwm.z.so"
    ":libwmutil.z.so"
    ":libz.so"
    ":libzuri.z.so"
    ;
#endif
