// skia_rtti_shim.cpp
//
// Provides Itanium C++ ABI typeinfo symbols (_ZTI*, _ZTS*) for the Skia
// classes that Android libhwui references at link time when libhwui is
// compiled with -frtti and inherits from Skia base classes.
//
// Rationale: OH's libskia_canvaskit.z.so is built with -fno-rtti, so it
// does not export typeinfo symbols for any Sk* class. When libhwui defines
// a subclass of e.g. SkDrawable, its compiler emits a typeinfo node for
// that subclass which references the base's typeinfo as an external
// undefined symbol (_ZTI10SkDrawable). Without a provider, the libhwui
// link fails (or, under --unresolved-symbols=ignore, the reference is
// silently nulled out).
//
// This shim provides those base typeinfo symbols WITHOUT replacing OH's
// libskia_canvaskit.z.so. An accompanying audit of frameworks/libs/hwui
// (2026-04-12) confirmed zero dynamic_cast<Sk*> / typeid(Sk*) call sites,
// so the shim only needs to satisfy the link-time symbol requirement;
// runtime RTTI behavior on pure-Skia objects is not exercised.
//
// Export control:
//   - Compiled with -frtti (required to emit _ZTI*/_ZTS*)
//   - Compiled with -fvisibility=hidden
//   - Linked with a version script (skia_rtti_shim.ver) that globalizes
//     only _ZTI* and _ZTS*. Vtables (_ZTV*), destructors, and other
//     compiler-emitted symbols stay LOCAL and cannot collide with the
//     real symbols exported by libskia_canvaskit.z.so at load time.
//
// Discovery of the class list: see discover_skia_rtti_syms.sh. The
// included skia_class_list.inc is regenerated by that script from the
// set of undefined _ZTI* symbols observed when libhwui is linked against
// OH's original libskia_canvaskit.z.so.

// Each entry declares a top-level polymorphic class whose mangled name
// matches the real Skia class. The compiler emits _ZTI<len><name> and
// _ZTS<len><name> for it. The anchored virtual destructor forces vtable
// and typeinfo emission.
//
// visibility("default") on the class is CRITICAL under -fvisibility=hidden:
// without it, clang marks _ZTI/_ZTS/_ZTV as hidden and they never make
// it into the dynamic symbol table, so the version script cannot export
// them. The attribute forces all three into .dynsym with default binding;
// the version script (skia_rtti_shim.ver) then keeps only _ZTI*/_ZTS*
// as GLOBAL and downgrades _ZTV* / destructor symbols to LOCAL, which
// prevents them from colliding with the real Skia exports at runtime.
#define SKIA_RTTI_CLASS(name)                          \
    class __attribute__((visibility("default"))) name  \
    {                                                  \
    public:                                            \
        virtual ~name();                               \
    };                                                 \
    name::~name() {}

// For classes that libhwui downcasts through a non-trivial inheritance
// chain, declare the chain explicitly so the emitted __si_class_type_info
// node carries a correct base pointer. Default path uses SKIA_RTTI_CLASS
// (base-less). Escalate to SKIA_RTTI_DERIVED only when runtime dynamic_cast
// through this base is observed by libhwui (not currently needed per audit).
#define SKIA_RTTI_DERIVED(name, base)                  \
    class __attribute__((visibility("default"))) base; \
    class __attribute__((visibility("default"))) name  \
        : public base                                  \
    {                                                  \
    public:                                            \
        virtual ~name();                               \
    };                                                 \
    name::~name() {}

#include "skia_class_list.inc"
