// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.eap.EapSessionConfig — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net.eap;

public class EapSessionConfig {
    public EapSessionConfig() {}
    public static class Builder {
        public Builder() {}
    }
    public static class EapAkaConfig {
        public EapAkaConfig() {}
    }
    public static class EapAkaPrimeConfig {
        public EapAkaPrimeConfig() {}
    }
    public static class EapMethodConfig {
        public EapMethodConfig() {}
    }
    public static class EapMsChapV2Config {
        public EapMsChapV2Config() {}
    }
    public static class EapSimConfig {
        public EapSimConfig() {}
    }
    public static class EapTtlsConfig {
        public EapTtlsConfig() {}
    }
    public static class EapUiccConfig {
        public EapUiccConfig() {}
    }
}
