// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.app.appsearch.AppSearchSchema — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.app.appsearch;

public class AppSearchSchema {
    public AppSearchSchema() {}
    public static class BooleanPropertyConfig {
        public BooleanPropertyConfig() {}
        public static class Builder {
            public Builder() {}
        }
    }
    public static class Builder {
        public Builder() {}
    }
    public static class BytesPropertyConfig {
        public BytesPropertyConfig() {}
        public static class Builder {
            public Builder() {}
        }
    }
    public static class DocumentPropertyConfig {
        public DocumentPropertyConfig() {}
        public static class Builder {
            public Builder() {}
        }
    }
    public static class LongPropertyConfig {
        public LongPropertyConfig() {}
        public static class Builder {
            public Builder() {}
        }
    }
    public static class PropertyConfig {
        public PropertyConfig() {}
    }
    public static class StringPropertyConfig {
        public StringPropertyConfig() {}
        public static class Builder {
            public Builder() {}
        }
    }
}
