// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.app.role.OnRoleHoldersChangedListener — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.app.role;

public class OnRoleHoldersChangedListener {
    public OnRoleHoldersChangedListener() {}
}
