// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.provider.MediaStore — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.provider;

public class MediaStore {
    public MediaStore() {}
    public static class Audio {
        public Audio() {}
        public static class Media {
            public Media() {}
        }
    }
    public static class Files {
        public Files() {}
    }
    public static class Images {
        public Images() {}
        public static class Media {
            public Media() {}
        }
        public static class Thumbnails {
            public Thumbnails() {}
        }
    }
    public static class Video {
        public Video() {}
        public static class Media {
            public Media() {}
        }
    }
}
