// Auto-generated by scan_bcp_class_gap.py (B.16/B.18), then hand-augmented (overall_design §15.1 第 3 条
// principle: HelloWorld 必需路径 → 手工补 method 真路由).
// org.ccil.cowan.tagsoup.Parser — mainline stub.
//
// T7 (#91 / #wikipedia): the empty stub lacked setProperty(String,Object), so wikipedia's HTML render
// path (org.wikipedia ComposeInternal -> tagsoup) hit
//   NoSuchMethodError: No virtual method setProperty(Ljava/lang/String;Ljava/lang/Object;)V
//   in class Lorg/ccil/cowan/tagsoup/Parser; ... appears in adapter-mainline-stubs.jar
// setProperty/getProperty below match upstream TagSoup's four recognized properties (unknown name ->
// SAXNotRecognizedException). Fields are Object because this stub does not parse; the real Scanner/
// Schema/AutoDetector types are not stubbed here.
//
// IMPORTANT (reported to the outer loop): this class is OTHERWISE an empty stub (only a constructor).
// setProperty passing only exposes the NEXT missing Parser method (setContentHandler/setFeature/parse);
// wikipedia's actual HTML rendering needs the full upstream TagSoup Parser + Scanner + HTMLScanner +
// Schema/HTMLSchema + HTMLModels + AutoDetector + Element/ElementType/AttributesImpl ported into the
// mainline-stubs jar. This file is the first hand-routed method; the full port is the #91 follow-on.
package org.ccil.cowan.tagsoup;

import org.xml.sax.SAXNotRecognizedException;
import org.xml.sax.SAXNotSupportedException;

public class Parser {
    /** The four property names TagSoup's own Parser.setProperty recognizes (upstream constants). */
    public static final String lexicalHandlerProperty = "http://xml.org/sax/properties/lexical-handler";
    public static final String scannerProperty = "http://www.ccil.org/~cowan/tagsoup/properties/scanner";
    public static final String schemaProperty = "http://www.ccil.org/~cowan/tagsoup/properties/schema";
    public static final String autoDetectorProperty =
            "http://www.ccil.org/~cowan/tagsoup/properties/auto-detector";

    private Object theLexicalHandler;
    private Object theScanner;
    private Object theSchema;
    private Object theAutoDetector;

    public Parser() {}

    public void setProperty(String name, Object value)
            throws SAXNotRecognizedException, SAXNotSupportedException {
        if (name == null) throw new NullPointerException("property name");
        if (name.equals(lexicalHandlerProperty)) {
            theLexicalHandler = value;
        } else if (name.equals(scannerProperty)) {
            theScanner = value;
        } else if (name.equals(schemaProperty)) {
            theSchema = value;
        } else if (name.equals(autoDetectorProperty)) {
            theAutoDetector = value;
        } else {
            throw new SAXNotRecognizedException("Unknown property " + name);
        }
    }

    public Object getProperty(String name) throws SAXNotRecognizedException {
        if (name == null) throw new NullPointerException("property name");
        if (name.equals(lexicalHandlerProperty)) return theLexicalHandler;
        if (name.equals(scannerProperty)) return theScanner;
        if (name.equals(schemaProperty)) return theSchema;
        if (name.equals(autoDetectorProperty)) return theAutoDetector;
        throw new SAXNotRecognizedException("Unknown property " + name);
    }
}
