// bionic_compat/include/statslog_art.h
// Stub for ART statsd logging constants.
// In a normal AOSP build, this is auto-generated from stats.proto.
// For cross-compilation on OH, we provide stub constants (logging is no-op).
#ifndef ART_STATSLOG_ART_H
#define ART_STATSLOG_ART_H

namespace android {
namespace art {

// Stub atom IDs - real values don't matter since OH doesn't use statsd
enum {
    ART_DATUM_REPORTED = 332,
    ART_DEVICE_DATUM_REPORTED = 550,
    ART_DATUM_DELTA_REPORTED = 565,
};

// ART datum ID enum (metrics framework)
enum ArtDatumId {
    ART_DATUM_INVALID = 0,
    ART_DATUM_GC_WORLD_STOP_TIME_AVG_MICROS = 1,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_TIME_HISTO_MILLIS = 2,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_TIME_HISTO_MILLIS = 3,
    ART_DATUM_JIT_METHOD_COMPILE_TIME_MICROS = 4,
    ART_DATUM_AOT_COMPILE_TIME = 5,
    ART_DATUM_CLASS_VERIFICATION_TIME_COUNTER_MICROS = 6,
    ART_DATUM_CLASS_LOADING_TIME_COUNTER_MICROS = 7,
    ART_DATUM_GC_TOTAL_BYTES_ALLOCATED = 8,
    ART_DATUM_GC_TOTAL_METADATA_SIZE_BYTES = 9,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_COUNT = 10,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_COUNT = 11,
    ART_DATUM_GC_TOTAL_COLLECTION_TIME_MS = 12,
    ART_DATUM_INTERPRETER_TO_COMPILED_CODE_BRIDGE_INVOCATIONS = 13,
    ART_DATUM_JIT_METHOD_COMPILE_COUNT = 14,
    ART_DATUM_YOUNG_GC_THROUGHPUT = 15,
    ART_DATUM_FULL_GC_THROUGHPUT = 16,
    ART_DATUM_YOUNG_GC_TRACING_THROUGHPUT = 17,
    ART_DATUM_FULL_GC_TRACING_THROUGHPUT = 18,
    ART_DATUM_GC_WORLD_STOP_COUNT = 19,
    ART_DATUM_GC_YOUNG_GENERATION_TRACING_TIME_HISTO_MILLIS = 20,
    ART_DATUM_GC_FULL_HEAP_TRACING_TIME_HISTO_MILLIS = 21,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_SCANNED_BYTES = 22,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_FREED_BYTES = 23,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_DURATION_MS = 24,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_SCANNED_BYTES = 25,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_FREED_BYTES = 26,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_DURATION_MS = 27,
    ART_DATUM_JIT_METHOD_COMPILE_TIME_HISTO_MICROS = 28,
    ART_DATUM_GC_WORLD_STOP_TIME_US_HISTO = 29,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_RECLAIM_RATE_HISTO = 30,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_RECLAIM_RATE_HISTO = 31,
    ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_BYTES_SURVIVING_HISTO = 32,
    ART_DATUM_GC_FULL_HEAP_COLLECTION_BYTES_SURVIVING_HISTO = 33,
    // ... additional metrics follow same pattern up to ~98
    ART_DATUM_PEAK_NATIVE_FREE_BYTES = 90,
    ART_DATUM_GC_TOTAL_TIME_SPENT_BLOCKING_GC_MS = 91,
    ART_DATUM_TOTAL_GCS_COUNT = 92,
    ART_DATUM_TOTAL_BLOCKING_GCS_COUNT = 93,
    ART_DATUM_MUTATOR_PAUSE_TIME_AVG = 94,
    ART_DATUM_GC_MARK_TIME_AVG = 95,
    ART_DATUM_GC_MARK_THROUGHPUT = 96,
    ART_DATUM_GC_COMPACTION_TIME_AVG = 97,
    ART_DATUM_GC_COMPACTION_THROUGHPUT = 98,
};

// GC type enum
enum ArtGcCollectorType {
    ART_GC_COLLECTOR_TYPE_MARK_SWEEP = 1,
    ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_SWEEP = 2,
    ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_COMPACT = 3,
    ART_GC_COLLECTOR_TYPE_SEMI_SPACE = 4,
    ART_GC_COLLECTOR_TYPE_CONCURRENT_COPYING = 5,
    ART_GC_COLLECTOR_TYPE_MARK_COMPACT = 6,
};

// ISA enum
enum ArtISA {
    ART_ISA_UNKNOWN = 0,
    ART_ISA_ARM = 1,
    ART_ISA_ARM64 = 2,
    ART_ISA_X86 = 3,
    ART_ISA_X86_64 = 4,
    ART_ISA_RISCV64 = 5,
};

// Compile filter
enum ArtCompileFilter {
    ART_COMPILATION_FILTER_UNKNOWN = 0,
    ART_COMPILATION_FILTER_ASSUMED_VERIFIED = 1,
    ART_COMPILATION_FILTER_EXTRACT = 2,
    ART_COMPILATION_FILTER_VERIFY = 3,
    ART_COMPILATION_FILTER_QUICKEN = 4,
    ART_COMPILATION_FILTER_SPACE_PROFILE = 5,
    ART_COMPILATION_FILTER_SPACE = 6,
    ART_COMPILATION_FILTER_SPEED_PROFILE = 7,
    ART_COMPILATION_FILTER_SPEED = 8,
    ART_COMPILATION_FILTER_EVERYTHING_PROFILE = 9,
    ART_COMPILATION_FILTER_EVERYTHING = 10,
    ART_COMPILATION_FILTER_ERROR = 11,
};

// Reason
enum ArtCompilationReason {
    ART_COMPILATION_REASON_UNKNOWN = 0,
    ART_COMPILATION_REASON_FIRST_BOOT = 1,
    ART_COMPILATION_REASON_BOOT_AFTER_OTA = 2,
    ART_COMPILATION_REASON_POST_BOOT = 3,
    ART_COMPILATION_REASON_INSTALL = 4,
    ART_COMPILATION_REASON_INSTALL_FAST = 5,
    ART_COMPILATION_REASON_INSTALL_BULK = 6,
    ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY = 7,
    ART_COMPILATION_REASON_INSTALL_BULK_DOWNGRADED = 8,
    ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY_DOWNGRADED = 9,
    ART_COMPILATION_REASON_BG_DEXOPT = 10,
    ART_COMPILATION_REASON_AB_OTA = 11,
    ART_COMPILATION_REASON_INACTIVE = 12,
    ART_COMPILATION_REASON_CMDLINE = 13,
    ART_COMPILATION_REASON_ERROR = 14,
    ART_COMPILATION_REASON_VDEX = 15,
    ART_COMPILATION_REASON_BOOT_AFTER_MAINLINE_UPDATE = 16,
};

// Stub: stats_write function (no-op on OH)
inline int stats_write(int /*atom_id*/, ...) { return 0; }

} // namespace art
} // namespace android

#endif // ART_STATSLOG_ART_H
