#ifndef VNDK_WINDOW_H_STUB
#define VNDK_WINDOW_H_STUB
// Minimal stub for vndk/window.h - no actual ANativeWindow_query overload to avoid conflict
#include <android/native_window.h>
#endif

#ifndef ANATIVEWINDOW_PERFORM_SET_USAGE
#define ANATIVEWINDOW_PERFORM_SET_USAGE    0
#endif
#ifndef ANATIVEWINDOW_PERFORM_SET_USAGE64
#define ANATIVEWINDOW_PERFORM_SET_USAGE64  30
#endif
#ifndef ANATIVEWINDOW_PERFORM_SET_BUFFERS_GEOMETRY
#define ANATIVEWINDOW_PERFORM_SET_BUFFERS_GEOMETRY NATIVE_WINDOW_SET_BUFFERS_GEOMETRY
#endif
#ifndef ANATIVEWINDOW_PERFORM_SET_BUFFERS_FORMAT
#define ANATIVEWINDOW_PERFORM_SET_BUFFERS_FORMAT NATIVE_WINDOW_SET_BUFFERS_FORMAT
#endif
#ifndef ANATIVEWINDOW_QUERY_MIN_UNDEQUEUED_BUFFERS
#define ANATIVEWINDOW_QUERY_MIN_UNDEQUEUED_BUFFERS NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS
#endif
