// AUTO-GENERATED by gen_mainline_initializer_stubs.sh.
// Edit only if a real OH-side service replaces the no-op.
package android.nfc;

/** Mainline APEX stub.  The real impl lives in an APEX module
 * that OH does not ship; stubs the call sites in
 * SystemServiceRegistry.<clinit> +
 * ActivityThread.initializeMainlineModules so they link cleanly. */
public final class NfcFrameworkInitializer {
    private NfcFrameworkInitializer() {}
    public static void registerServiceWrappers() { /* no-op */ }
    public static void setNfcServiceManager(android.nfc.NfcServiceManager a0) { /* no-op */ }
}
