// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.ipsec.ike.ike3gpp.Ike3gppExtension — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net.ipsec.ike.ike3gpp;

public class Ike3gppExtension {
    public Ike3gppExtension() {}
}
