// AUTO-GENERATED by gen_mainline_initializer_stubs.sh.
// Edit only if a real OH-side service replaces the no-op.
package android.net;

import android.app.SystemServiceRegistry;
import android.content.Context;

/** Mainline APEX stub.  The real impl lives in an APEX module
 * that OH does not ship; stubs the call sites in
 * SystemServiceRegistry.<clinit> +
 * ActivityThread.initializeMainlineModules so they link cleanly.
 *
 * [WL-CONNECTIVITY 2026-06-27] No longer a no-op: registers a non-null
 * ConnectivityManager service wrapper.  AOSP apps (e.g. WorkManager's
 * NetworkStateTracker) do
 *     getSystemService("connectivity") as android.net.ConnectivityManager
 * and a null result is a hard Kotlin non-null cast NPE.  OH ships no
 * Connectivity APEX binder, so the wrapper is a no-network stub that
 * answers "no active network" for every query — enough for the app to
 * proceed past onCreate without crashing.  This is the canonical mainline
 * registration path (SystemServiceRegistry.<clinit> ->
 * ConnectivityFrameworkInitializer.registerServiceWrappers), not an
 * ART/class-linker change. */
public final class ConnectivityFrameworkInitializer {
    private ConnectivityFrameworkInitializer() {}
    public static void registerServiceWrappers() {
        SystemServiceRegistry.registerContextAwareService(
                Context.CONNECTIVITY_SERVICE,
                ConnectivityManager.class,
                new SystemServiceRegistry
                        .ContextAwareServiceProducerWithoutBinder<ConnectivityManager>() {
                    @Override
                    public ConnectivityManager createService(Context context) {
                        return new ConnectivityManager(context);
                    }
                });
    }
}
