// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.NetworkRequest — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net;

public class NetworkRequest {
    public NetworkRequest() {}
    // [WL-CONNECTIVITY 2026-06-27] Builder used by noice getInternetConnectivityFlow:
    //   new NetworkRequest.Builder().addCapability(12).build()
    // OH has no Connectivity binder; the built request is an inert token handed
    // to ConnectivityManager.registerNetworkCallback (a no-op stub).
    public static class Builder {
        public Builder() {}
        public Builder addCapability(int capability) { return this; }
        public Builder removeCapability(int capability) { return this; }
        public Builder addTransportType(int transportType) { return this; }
        public Builder removeTransportType(int transportType) { return this; }
        public NetworkRequest build() { return new NetworkRequest(); }
    }
}
