// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.NetworkCapabilities — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net;

public class NetworkCapabilities {
    public NetworkCapabilities() {}
    // [WL-CONNECTIVITY 2026-06-27] no-network stub answers (hasCapability /
    // hasTransport used by WorkManager NetworkApi21 + noice ext).  Reached only
    // on a non-null NetworkCapabilities, which cm.getNetworkCapabilities()
    // never returns here; provided for link coherence.
    public boolean hasCapability(int capability) { return false; }
    public boolean hasTransport(int transportType) { return false; }
}
