// Auto-generated by scan_bcp_class_gap.py (B.16/B.18)
// android.net.NetworkInfo — empty mainline stub + nested inner classes
// Per overall_design §15.1 第 3 条原则:
//   HelloWorld 不需要 → 空 stub；HelloWorld 必需路径 → 手工补 method 真路由
package android.net;

public class NetworkInfo {
    public NetworkInfo() {}
    // [WL-CONNECTIVITY 2026-06-27] no-network stub answers used by app paths
    // (WorkManager NetworkStateTracker, noice ext).  cm.getActiveNetworkInfo()
    // returns null so these are normally not reached, but provide them for
    // link coherence and any direct caller.
    public boolean isConnected() { return false; }
    public boolean isConnectedOrConnecting() { return false; }
    public boolean isAvailable() { return false; }
    public boolean isRoaming() { return false; }
    public int getType() { return -1; }
    public static class DetailedState {
        public DetailedState() {}
    }
}
