#!/usr/bin/env python3
"""Generate the immutable A06 generation seal as a compiled C object."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import struct
import uuid


MAGIC = 0x574C474D45544131
ABI_VERSION = 1
STRUCT_SIZE = 240
SHA256_BYTES = 32
MANIFEST_DIGEST_PATTERN = re.compile(
    r"static const WlscplManifestV2 kWlscplManifest.*?"
    r"\{(?P<values>(?:\s*UINT8_C\(0x[0-9a-f]{2}\),?){32})\},",
    re.DOTALL,
)
HEX_BYTE_PATTERN = re.compile(r"UINT8_C\(0x([0-9a-f]{2})\)")


def digest_arg(value: str, name: str) -> bytes:
    if not re.fullmatch(r"[0-9a-f]{64}", value):
        raise ValueError(f"{name} must be 64 lowercase hex characters")
    decoded = bytes.fromhex(value)
    if not any(decoded):
        raise ValueError(f"{name} must be nonzero")
    return decoded


def read_manifest_digest(source: Path) -> bytes:
    if not source.is_file():
        raise ValueError(f"manifest source is absent: {source}")
    match = MANIFEST_DIGEST_PATTERN.search(source.read_text(encoding="utf-8"))
    if match is None:
        raise ValueError("manifest source has no generated V2 manifest digest")
    values = HEX_BYTE_PATTERN.findall(match.group("values"))
    if len(values) != SHA256_BYTES:
        raise ValueError("manifest source digest is not exactly 32 bytes")
    return bytes(int(value, 16) for value in values)


def c_bytes(data: bytes) -> str:
    return ", ".join(f"UINT8_C(0x{value:02x})" for value in data)


def canonical_digest(
    boot_id: bytes,
    artifact_generation: bytes,
    policy_epoch: int,
    launch_generation: int,
    manifest_digest: bytes,
    hook_digest: bytes,
    policy_provenance_digest: bytes,
) -> bytes:
    canonical = b"".join(
        (
            struct.pack("<QII", MAGIC, ABI_VERSION, STRUCT_SIZE),
            boot_id,
            artifact_generation,
            struct.pack("<QQ", policy_epoch, launch_generation),
            manifest_digest,
            hook_digest,
            policy_provenance_digest,
        )
    )
    if len(canonical) != 176:
        raise AssertionError("metadata canonical schema size drift")
    return hashlib.sha256(canonical).digest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-generation-digest", required=True)
    parser.add_argument("--manifest-digest", required=True)
    parser.add_argument("--manifest-source", required=True, type=Path)
    parser.add_argument("--hook-digest", required=True)
    parser.add_argument("--policy-epoch", required=True, type=int)
    parser.add_argument("--policy-provenance-digest", required=True)
    parser.add_argument("--launch-generation", required=True, type=int)
    parser.add_argument("--boot-id", required=True)
    parser.add_argument("--output-c", required=True, type=Path)
    args = parser.parse_args()

    artifact_generation = digest_arg(
        args.artifact_generation_digest, "artifact generation digest"
    )
    manifest_digest = digest_arg(args.manifest_digest, "manifest digest")
    hook_digest = digest_arg(args.hook_digest, "hook digest")
    policy_provenance_digest = digest_arg(
        args.policy_provenance_digest, "policy provenance digest"
    )
    if artifact_generation in (manifest_digest, hook_digest):
        raise ValueError(
            "whole-generation composite digest must be distinct from component digests"
        )
    if args.policy_epoch <= 0 or args.launch_generation <= 0:
        raise ValueError("policy epoch and launch generation must be nonzero")
    canonical_boot_id = str(uuid.UUID(args.boot_id))
    if canonical_boot_id != args.boot_id:
        raise ValueError("boot id must use canonical lowercase UUID spelling")
    boot_id = uuid.UUID(canonical_boot_id).bytes
    if not any(boot_id):
        raise ValueError("boot id must be nonzero")
    source_manifest_digest = read_manifest_digest(args.manifest_source)
    if source_manifest_digest != manifest_digest:
        raise ValueError("manifest source and --manifest-digest are mixed-generation")
    if args.artifact_generation_digest not in args.manifest_source.read_text(
        encoding="utf-8"
    ):
        raise ValueError(
            "manifest deployment paths do not name the whole-generation digest"
        )

    metadata_digest = canonical_digest(
        boot_id,
        artifact_generation,
        args.policy_epoch,
        args.launch_generation,
        manifest_digest,
        hook_digest,
        policy_provenance_digest,
    )
    output = f"""/* Generated by generate_generation_metadata.py; do not edit. */
#include "westlake_generation_identity_facts.h"

static const WlgrIfGenerationMetadata kWlgrBuildGeneratedMetadata = {{
    WLGR_IF_METADATA_MAGIC,
    WLGR_IF_ABI_VERSION,
    (uint32_t)sizeof(WlgrIfGenerationMetadata),
    {{{c_bytes(boot_id)}}},
    {{{c_bytes(artifact_generation)}}},
    UINT64_C({args.policy_epoch}),
    UINT64_C({args.launch_generation}),
    {{{c_bytes(manifest_digest)}}},
    {{{c_bytes(hook_digest)}}},
    {{{c_bytes(policy_provenance_digest)}}},
    {{{c_bytes(metadata_digest)}}},
    {{0}},
}};

const WlgrIfGenerationMetadata *WlgrIfGetBuildGeneratedMetadata(void)
{{
    return &kWlgrBuildGeneratedMetadata;
}}
"""
    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_c.write_text(output, encoding="utf-8")
    print(
        "GENERATION_METADATA "
        f"artifact_generation={artifact_generation.hex()} "
        f"manifest_digest={manifest_digest.hex()} "
        f"hook_digest={hook_digest.hex()} "
        f"policy_epoch={args.policy_epoch} "
        f"policy_provenance={policy_provenance_digest.hex()} "
        f"launch_generation={args.launch_generation} "
        f"boot_id={canonical_boot_id} "
        f"metadata_digest={metadata_digest.hex()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
