#!/usr/bin/env python3
"""Generate only the BMP Lu/Nd data consumed by Android SDK string rules."""
import argparse
import hashlib
from pathlib import Path

SOURCE_SHA256 = "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f"
p = argparse.ArgumentParser()
p.add_argument("--unicode-data", required=True, type=Path)
p.add_argument("--output", required=True, type=Path)
args = p.parse_args()
data = args.unicode_data.read_bytes()
if hashlib.sha256(data).hexdigest() != SOURCE_SHA256:
    raise SystemExit("Android r4 ICU UnicodeData source hash mismatch")
uppercase, digits = [], {}
for line in data.decode().splitlines():
    fields = line.split(';')
    cp = int(fields[0], 16)
    if cp > 0xffff:
        continue
    if fields[2] == 'Lu':
        uppercase.append(cp)
    if fields[2] == 'Nd':
        digits[cp] = int(fields[6])
ranges = []
for cp in uppercase:
    if ranges and ranges[-1][1] + 1 == cp:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp])
zeros = [cp for cp, value in digits.items() if value == 0]
assert {cp + n: n for cp in zeros for n in range(10)} == digits
lines = [
    '// Generated by tests/oracle/generate_android_character_tables.py; do not edit.',
    '// Android android-16.0.0_r4 external/icu UnicodeData.txt, Unicode 16.0.',
    '// SPDX-License-Identifier: Unicode-3.0',
    '// Copyright (c) 2024 Unicode, Inc. See android_character_data.LICENSE.',
    '// Source SHA256: ' + SOURCE_SHA256,
    '#ifndef OH_ADAPTER_ANDROID_CHARACTER_DATA_H',
    '#define OH_ADAPTER_ANDROID_CHARACTER_DATA_H',
    '#include <cstdint>',
    'namespace oh_adapter::application_attributes::android_character_data {',
    'struct Range { uint16_t first, last; };',
    'inline constexpr Range UPPERCASE[] = {',
]
lines += [f'    {{0x{first:04x}, 0x{last:04x}}},' for first, last in ranges]
lines += ['};', 'inline constexpr uint16_t DIGIT_ZERO[] = {']
lines += [f'    0x{cp:04x},' for cp in zeros]
lines += ['};', '}', '#endif', '']
args.output.write_text('\n'.join(lines))
print(f'Generated {len(ranges)} BMP Lu ranges and {len(zeros)} Nd digit sets')
